#$L$
# Copyright (C) 2011 Ridgerun (http://www.ridgerun.com)
##$L$

PKG_URL=git://github.com/RidgeRun/gst-openmax-dm81xx.git
PKG_TYPE=git
PKG_REVISION=bf54ccd7f396d7a980db79597743201f339e698c

AUTOTOOLS_SRC_DIR=src
# Prevents autogen from running configure
export NOCONFIGURE=yes

include ../../bsp/classes/rrsdk.class
include $(CLASSES)/gstreamer-plugin.class
