#$L$
# Copyright (C) 2011 Ridgerun (http://www.ridgerun.com). 
##$L$

PKG_URL=http://sourceforge.net/projects/strace/files/strace/4.5.20/
PKG_TARBALL=strace-4.5.20.tar.bz2
PKG_SHA1SUM=3f5c8874610d7e3d13fc1c8b2e5fb5513468c45a

BINARIES = /usr/bin/{strace,strace-graph}

include ../../../bsp/classes/rrsdk.class
include $(CLASSES)/autotools.class

