#$L$
# Copyright (C) 2013 Ridgerun (http://www.ridgerun.com). 
##$L$

PKG_URL=http://downloads.sourceforge.net/project/libtirpc/libtirpc/0.2.4
PKG_TARBALL=libtirpc-0.2.4.tar.bz2
PKG_SHA1SUM=1484e59eb9c0c6adf4b072f2b80ccb17465fd4a3

AUTOTOOLS_PARAMS = --sysconfdir=$(FSDEVROOT)/etc --disable-static --disable-gssapi

LIBRARIES=  /usr/lib/libtirpc.so.1.0.10
OTHERS = /etc/netconfig
include ../../../bsp/classes/rrsdk.defs
include $(CLASSES)/autotools.class


