#$L$
# Copyright (C) 2013 Ridgerun (http://www.ridgerun.com). 
##$L$

PKG_URL=git://git.debian.org/git/collab-maint/ltrace.git
PKG_REVISION=653085a32cdc89f5215c2d70249b58c9fe6aebb7

BINARIES = /usr/bin/ltrace
OTHERS = /usr/etc/ltrace.conf

include ../../../bsp/classes/rrsdk.class
include $(CLASSES)/autotools.class

